### ISSUE TITLE
Build faild

### ISSUE THREAD

**Issue by jaweii** [parse-community/Parse-SDK-Flutter#323]
```
[+4896 ms] [+4960 ms] 
[  +13 ms]            Compiler message:
[   +1 ms] [   +2 ms] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:29:19: Error:
The method 'clear' isn't defined for the class 'Database'.
[   +1 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'clear'.
[        ] [        ]     return _store.clear();
[        ] [        ]                   ^^^^^
[   +3 ms] [   +5 ms] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:34:19: Error:
The method 'containsKey' isn't defined for the class 'Database'.
[   +4 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +7 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'containsKey'.
[  +10 ms] [        ]     return _store.containsKey(key);
[  +13 ms] [        ]                   ^^^^^^^^^^^
[   +1 ms] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:39:19: Error:
The method 'get' isn't defined for the class 'Database'.
[   +1 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'get'.
[        ] [        ]     return _store.get(key);
[   +1 ms] [        ]                   ^^^
[        ] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:44:42: Error:
The method 'get' isn't defined for the class 'Database'.
[   +1 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'get'.
[   +2 ms] [        ]     final bool storedItem = await _store.get(key);
[   +1 ms] [        ]                                          ^^^
[        ] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:50:44: Error:
The method 'get' isn't defined for the class 'Database'.
[   +1 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'get'.
[        ] [        ]     final double storedItem = await _store.get(key);
[        ] [        ]                                            ^^^
[   +1 ms] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:56:41: Error:
The method 'get' isn't defined for the class 'Database'.
[   +1 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'get'.
[   +1 ms] [        ]     final int storedItem = await _store.get(key);
[        ] [        ]                                         ^^^
[        ] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:62:44: Error:
The method 'get' isn't defined for the class 'Database'.
[   +2 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'get'.
[        ] [        ]     final String storedItem = await _store.get(key);
[        ] [        ]                                            ^^^
[        ] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:68:50: Error:
The method 'get' isn't defined for the class 'Database'.
[        ] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'get'.
[        ] [        ]     final List<String> storedItem = await _store.get(key);
[        ] [        ]                                                  ^^^
[        ] [   +2 ms] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:74:19: Error:
The method 'delete' isn't defined for the class 'Database'.
[  +13 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +2 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'delete'.
[   +3 ms] [        ]     return _store.delete(key);
[   +3 ms] [        ]                   ^^^^^^
[        ] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:79:19: Error:
The method 'put' isn't defined for the class 'Database'.
[   +1 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +2 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'put'.
[   +7 ms] [        ]     return _store.put(value, key);
[   +1 ms] [        ]                   ^^^
[   +3 ms] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:84:19: Error:
The method 'put' isn't defined for the class 'Database'.
[   +4 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[  +12 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'put'.
[   +1 ms] [        ]     return _store.put(value, key);
[   +2 ms] [        ]                   ^^^
[   +5 ms] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:89:19: Error:
The method 'put' isn't defined for the class 'Database'.
[   +5 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[   +4 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'put'.
[  +16 ms] [        ]     return _store.put(value, key);
[  +14 ms] [        ]                   ^^^
[  +47 ms] [        ] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:94:19: Error:
The method 'put' isn't defined for the class 'Database'.
[  +47 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[  +51 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'put'.
[  +37 ms] [        ]     return _store.put(value, key);
[  +13 ms] [        ]                   ^^^
[  +38 ms] [   +1 ms] /C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/parse_server_sdk-1.0.24/lib/src/storage/core_store_sem_impl.dart:99:19: Error:
The method 'put' isn't defined for the class 'Database'.
[  +19 ms] [        ]  - 'Database' is from 'package:sembast/src/api/v2/database.dart'
('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/sembast-2.3.0/lib/src/api/v2/database.dart').
[  +23 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named 'put'.
[  +42 ms] [        ]     return _store.put(values, key);
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.3, on Microsoft Windows [Version 10.0.17134.1], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by phillwiggins** [comment]
Hey

Are you directly importing v1.0.25 from GitHub? If so, please point it to 1.0.25, or pull the release version of 1.0.25 from pub get.

**Comment by jaweii** [comment]
@phillwiggins I have point it to 1.0.25 from pub get, but there is stille the error.
Can you give me a example how to point it to 1.0.26 from GitHub please?

```
 # I don't know how to spacify the version
  parse_server_sdk: 
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
```

**Comment by phillwiggins** [comment]
parse_server_sdk:
    git:
      url: git://github.com/phillwiggins/flutter_parse_sdk.git
      ref: release/1.0.26

I will release this version today at some point. Let me know if the issue persists.

**Comment by jaweii** [comment]
Now a new  error was occuared:

```
[+3098 ms] [+3138 ms] 
[   +2 ms]            Compiler message:
[        ] [   +1 ms] lib/models/user.dart:145:58: Error: Too few positional arguments: 1 required, 0 given.
[        ] [        ]     final user = await ParseUser.getCurrentUserFromServer(token: token.result);
[        ] [        ]                                                          ^
[        ] [        ] /C:/flutter/.pub-cache/git/Parse-SDK-Flutter-6a0ae4c9409e88267eb119499863f5e192a879af/lib/src/objects/parse_user.dart:89:32:
Context: Found this candidate, but the arguments don't match.
[   +1 ms] [        ]   static Future<ParseResponse> getCurrentUserFromServer(String token,
[        ] [        ]                                ^^^^^^^^^^^^^^^^^^^^^^^^
[+6293 ms] [+6234 ms] Persisting file store
[   +1 ms] [  +18 ms] Done persisting file store
[   +1 ms] [   +1 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[        ] build failed.
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
[        ] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:183:7)
[        ] [  +11 ms] "flutter assemble" took 11,982ms.
[        ] <asynchronous suspension>
[   +2 ms] #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
[        ] <asynchronous suspension>
[   +1 ms] #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
[   +1 ms] <asynchronous suspension>
[        ] #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[        ] #5      _rootRun (dart:async/zone.dart:1126:13)
[        ] #6      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #7      _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #8      runZoned (dart:async/zone.dart:1465:12)
[   +2 ms] #9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[        ] #10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
[        ] #11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
[        ] #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
[        ] <asynchronous suspension>
[        ] #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[        ] #14     _rootRun (dart:async/zone.dart:1126:13)
[   +1 ms] #15     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #16     _runZoned (dart:async/zone.dart:1518:10)
[        ] #17     runZoned (dart:async/zone.dart:1465:12)
[        ] #18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[        ] #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
[   +1 ms] #20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
[        ] #21     new Future.sync (dart:async/future.dart:224:31)
[        ] #22     CommandRunner.run (package:args/command_runner.dart:112:14)
[        ] #23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
[        ] #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
[        ] #25     _rootRun (dart:async/zone.dart:1126:13)
[        ] #26     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #27     _runZoned (dart:async/zone.dart:1518:10)
[        ] #28     runZoned (dart:async/zone.dart:1502:12)
[        ] #29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
[        ] <asynchronous suspension>
[        ] #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[        ] #31     _rootRun (dart:async/zone.dart:1126:13)
[        ] #32     _CustomZone.run (dart:async/zone.dart:1023:19)
[   +1 ms] #33     _runZoned (dart:async/zone.dart:1518:10)
[        ] #34     runZoned (dart:async/zone.dart:1465:12)
[        ] #35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[        ] #36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
[        ] #37     run (package:flutter_tools/runner.dart:50:10)
[        ] #38     main (package:flutter_tools/executable.dart:65:9)
[   +1 ms] #39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[        ] #40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
[        ] #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[  +46 ms] > Task :app:compileFlutterBuildRelease FAILED
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get fullinsights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 21s
[        ] 26 actionable tasks: 1 executed, 25 up-to-date
[ +370 ms] Running Gradle task 'assembleRelease'... (completed in 21.8s)
[   +2 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
[   +7 ms] Building plugin admob_flutter...
[   +6 ms] Running Gradle task 'assembleAarRelease'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[  +14 ms] "flutter apk" took 22,647ms.
The plugin admob_flutter could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17134.1], locale zh-CN)                                                                                                                                                    [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)                                                                    [!] Android Studio (version 3.1)                                                                                                                     
  X Flutter plugin not installed; this adds Flutter specific functionality.                                                                        
  X Dart plugin not installed; this adds Dart specific functionality.                                                                              [√] Connected device (1 available)
                                                                                                                                                  ! Doctor found issues in 1 category.
```

How can i solve the problem?

**Comment by phillwiggins** [comment]
It doesn't really look like there is changes in this area. Can you post
some code?

**Comment by jaweii** [comment]
Solved.
Thank you!
