### ISSUE TITLE
CoreStore and parseUserConstructor initialization

### ISSUE THREAD

**Issue by ernestasga** [parse-community/Parse-SDK-Flutter#485]
I would like to implement coreStore and parseUserConstructor in `Parse().initialize()` to automaticly login user on app start but i'm having trouble.

 ```
 await Parse().initialize(
    'my.app.id',
    'http://10.0.2.2:1337/parse',
    debug: false,
    coreStore: await CoreStoreSharedPrefsImp.getInstance(),
    parseUserConstructor: (username, password, emailAddress,
            {client, debug, sessionToken}) =>
        User(username, password, emailAddress),
  );

```

Output:

```
E/flutter (31359): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (31359): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (31359): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (31359): #0      defaultBinaryMessenger.<anonymous closure> 
package:flutter/…/services/binary_messenger.dart:92
E/flutter (31359): #1      defaultBinaryMessenger 
package:flutter/…/services/binary_messenger.dart:105
E/flutter (31359): #2      MethodChannel.binaryMessenger 
package:flutter/…/services/platform_channel.dart:143
E/flutter (31359): #3      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:149
E/flutter (31359): #4      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:332
E/flutter (31359): #5      MethodChannel.invokeMapMethod 
package:flutter/…/services/platform_channel.dart:359
E/flutter (31359): #6      MethodChannelSharedPreferencesStore.getAll 
package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:54
E/flutter (31359): #7      SharedPreferences._getSharedPreferencesMap 
package:shared_preferences/shared_preferences.dart:191
E/flutter (31359): #8      SharedPreferences.getInstance 
package:shared_preferences/shared_preferences.dart:58
E/flutter (31359): #9      CoreStoreSharedPrefsImp.getInstance 
package:parse_server_sdk_flutter/…/storage/core_store_sp_impl.dart:11
E/flutter (31359): #10     init 
package:Khons/injection.dart:27
E/flutter (31359): #11     main 
package:Khons/main.dart:13
E/flutter (31359): #12     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:231:25))
E/flutter (31359): #13     _rootRun  (dart:async/zone.dart:1190:13))
E/flutter (31359): #14     _CustomZone.run  (dart:async/zone.dart:1093:19))
E/flutter (31359): #15     _runZoned  (dart:async/zone.dart:1630:10))
E/flutter (31359): #16     runZonedGuarded  (dart:async/zone.dart:1618:12))
E/flutter (31359): #17     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:223:5))
E/flutter (31359): #18     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19))
E/flutter (31359): #19     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12))
```

What am I missing?

**Comment by ernestasga** [comment]
Nevermind, had to call `WidgetsFlutterBinding.ensureInitialized();` before initializing...
