### ISSUE TITLE
Failed to close existing event stream

### ISSUE THREAD

**Issue by lucastsc** [parse-community/Parse-SDK-Flutter#524]
I was able to use LiveQuery in my flutter app. There were no problems and I was very happy with this.
However, things went wrong when I've changed the screen of my app.
I've made a Parse().initialize(...) in a screen (let's say screenA.dart), and then, in the (new) subsequent screen (let's say screenB.dart), reached using Navigator.push(...) I needed to use liveQuery. But, to use live query on screenB.dart it was necessary to Parse().initialize(...) again or any other way to recover my previous initialization. 

**My question is**: how to handle the Parse connection in a new file when in a previous file you've made a Parse().initialize before? I mean, how to correctly use liveQuery in a file in which you (are supposed to) don't have a Parse().initialize(...) again (because the connection was already made)?

Example:
ScreenA:
```
...
@override
  void initState() {
    super.initState();
    Parse().initialize(
        kParseApplicationId,
        kParseServerUrl,
        clientKey: kParseClientKey,
        masterKey: kParseMasterKey,
        debug: true,
        liveQueryUrl: kLiveQueryUrl,
        autoSendSessionId: true);
  }
...
Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => ScreenB()),
                );
```
ScreenB:
```
...
//supposed to connect again?I believe it is giving me the title-mentioned error...
@override
  void initState() {
    super.initState();
    Parse().initialize(
        kParseApplicationId,
        kParseServerUrl,
        clientKey: kParseClientKey,
        masterKey: kParseMasterKey,
        debug: true,
        liveQueryUrl: kLiveQueryUrl,
        autoSendSessionId: true);
  }

final ParseResponse response = await Parse().healthCheck();

    if (response.success) {
      await test();
      text += 'testing\n';
      print(text);
    } else {
      text += 'Server health check failed';
      print(text);
    }
  }

 Future<void> test() async {

    final LiveQuery liveQuery = LiveQuery();

    QueryBuilder<ParseObject> query =
    QueryBuilder<ParseObject>(ParseObject(widget.classNameDB));

    Subscription subscription = await liveQuery.client.subscribe(query);

    subscription.on(LiveQueryEvent.create, (value) {
      setState(() {

      });
      print('*** CREATE ***: ${DateTime.now().toString()}\n $value ');
      print((value as ParseObject).objectId);
      print((value as ParseObject).updatedAt);
      print((value as ParseObject).createdAt);
      print((value as ParseObject).get('objectId'));
      print((value as ParseObject).get('updatedAt'));
      print((value as ParseObject).get('createdAt'));
    });

    subscription.on(LiveQueryEvent.update, (value) {
      setState(() {

      });
      print('*** UPDATE ***: ${DateTime.now().toString()}\n $value ');
      print((value as ParseObject).objectId);
      print((value as ParseObject).updatedAt);
      print((value as ParseObject).createdAt);
      print((value as ParseObject).get('objectId'));
      print((value as ParseObject).get('updatedAt'));
      print((value as ParseObject).get('createdAt'));
    });

    subscription.on(LiveQueryEvent.delete, (value) {
      setState(() {

      });
      print('*** DELETE ***: ${DateTime.now().toString()}\n $value ');
      print((value as ParseObject).objectId);
      print((value as ParseObject).updatedAt);
      print((value as ParseObject).createdAt);
      print((value as ParseObject).get('objectId'));
      print((value as ParseObject).get('updatedAt'));
      print((value as ParseObject).get('createdAt'));
    });
  }
...
```
The logs are giving me the following:
```
E/EventChannel#plugins.flutter.io/connectivity_status(17269): Failed to close existing event stream
E/EventChannel#plugins.flutter.io/connectivity_status(17269): java.lang.IllegalArgumentException: NetworkCallback was not registered
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:52)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4235)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at io.flutter.plugins.connectivity.ConnectivityBroadcastReceiver.onCancel(ConnectivityBroadcastReceiver.java:53)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:182)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at android.os.Looper.loop(Looper.java:183)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/EventChannel#plugins.flutter.io/connectivity_status(17269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (17269): LiveQueryReconnectingController: ParseConnectivityResult.mobile
I/flutter (17269): LiveQueryReconnectingController: Retrytimer set to 0ms
I/flutter (17269): LiveQueryReconnectingController: ParseConnectivityResult.mobile
I/flutter (17269): LiveQueryReconnectingController: Retrytimer set to 500ms
I/flutter (17269): already connecting
I/flutter (17269): LiveQuery: : Socket opened
I/flutter (17269): LiveQuery: : ConnectMessage: {op: connect, applicationId: myAppId, clientKey: myClientKey, masterKey: myMasterKey}
I/flutter (17269): LiveQuery: : Listen: {"op":"connected","clientId":"8502f578-b895-491a-b91a-63fb98c7b745"}
I/flutter (17269): ReSubScription:{}
I/flutter (17269): LiveQueryReconnectingController: LiveQueryClientEvent.CONNECTED
I/flutter (17269): LiveQuery: : SubscribeMessage: {op: subscribe, requestId: 1, query: {className: empresa, where: {}}}
I/flutter (17269): testing
I/flutter (17269): LiveQuery: : Listen: {"op":"subscribed","clientId":"8502f578-b895-491a-b91a-63fb98c7b745","requestId":1}

```
Despite the fact that it seems to have opened a new connection, the live queries are not working in ScreenB.
Could someone try to me help me how to handle this?
Thanks in advance!

**Comment by RodrigoSMarques** [comment]
You should only start Parse once, usually on main.

Once the main has been initialized, it can be used in any routine afterwards.

**Comment by lucastsc** [comment]
However, if I don't initialize it again, it says 
`LiveQuery does not work, if there is ParseConnectivityProvider provided.`

**Comment by lucastsc** [comment]
I finally understood what was happening...
I was modifying only the flutter app (client side),without modifying the parse-server index.js file (the server file), in the lines that corresponds to the classes able to interpret live queries!
I realized that due to this I'm facing a big problem, because for my app proposal,it would be necessary to create a realtime database (dynamically created, based on user entry) where it could use the benefits of live queries.
However, it would be necessary to constantly change the server file, adding those names (remember,they would be created by user input).So, I believe that is not possible to accomplish this.Anyone have any idea?I mean, the possibility to live query any user-entered class name?

**Comment by RodrigoSMarques** [comment]
Great that discovered the problem.
But why does the class have to be dynamic?
What is the logic for this? Why should the user define the class?

**Comment by lucastsc** [comment]
Because the following:
The app will be used by clients and companies.The client will be able to see the companies available employees, and (the big thing) the company will be able to create a class with its own name to share its available employees.So...the thing is that a company whk have the app could create it's own class to share it's information...I haven't had a better idea ;(

**Comment by fischerscode** [comment]
You might be able to create a class called `CustomClasses`.
This class would have a string column called `className` instead of creating a new class, you could just introduce a new value for 'className'.
If you do this, I would recommend you to create a custom `QueryBuilder`-class.

> LiveQuery does not work, if there is ParseConnectivityProvider provided.

This might be related #523

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
