### ISSUE TITLE
Saving User

### ISSUE THREAD

**Issue by pastordee** [parse-community/Parse-SDK-Flutter#614]
I'm using version 3.0 and Every time I try to save data to users and other classes I get this error.

the update method doesn't work either

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      _ParseResponseBuilder._handleSuccess (package:parse_server_sdk/src/objects/response/parse_response_builder.dart:76:35)
#1      _ParseResponseBuilder.handleResponse (package:parse_server_sdk/src/objects/response/parse_response_builder.dart:29:14)
#2      handleResponse (package:parse_server_sdk/src/objects/response/parse_response_utils.dart:8:31)
#3      batchRequest (package:parse_server_sdk/src/utils/parse_utils.dart:82:12)
<asynchronous suspension>
#4      ParseObject._saveChildren (package:parse_server_sdk/src/objects/parse_object.dart:172:40)
<asynchronous suspension>
#5      ParseObject.save (package:parse_server_sdk/src/objects/parse_object.dart:99:44)
<asynchronous suspension>
#6      ParseUser.save (package:parse_server_sdk/src/objects/parse_user.dart:390:38)
<asynchronous suspension>

**Comment by chuonglam** [comment]
That's because v3.0 now supports null-safety checking. You can try to check nullable of the data before set it to the ParseUser object.

**Comment by RodrigoSMarques** [comment]
Closed. No activity in the last 14 days.
If necessary open again.
