### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by ulrivo** [parse-community/Parse-SDK-Flutter#648]
Hi,

my first steps with Parse-SDK-Flutter:

Build a simple test application as described on [Back4App](https://www.back4app.com/docs/flutter/parse-sdk/parse-flutter-sdk), running on a local parse-server and at Back4App, producing the following error:

E/flutter ( 6224): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 6224): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 6224): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 6224): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 6224): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
E/flutter ( 6224): #4      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:32)
E/flutter ( 6224): #5      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:66:42)
E/flutter ( 6224): #6      Parse.initialize (package:parse_server_sdk_flutter/parse_server_sdk.dart:67:57)
E/flutter ( 6224): #7      main (package:markdown/main.dart:12:17)
E/flutter ( 6224): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 6224): #9      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 6224): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 6224): #11     _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 6224): #12     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 6224): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 6224): #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 6224): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 6224):

**Comment by ulrivo** [comment]
The error disappears if you use **WidgetsFlutterBinding.ensureInitialized()** in void main() as shown below.

[Here](https://stackoverflow.com/questions/63873338/what-does-widgetsflutterbinding-ensureinitialized-do/63873689) is an explanation. But I dont understand the whole thing ;-)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final keyApplicationId = 'xxxx';
  final keyParseServerUrl = 'http://localhost:1337/parse';

  await Parse().initialize(keyApplicationId, keyParseServerUrl,
      autoSendSessionId: true);

  var firstObject = ParseObject('FirstClass')
    ..set(
        'message', 'Hey ! First message from Flutter. Parse is now connected');
  await firstObject.save();

  print('done');
}

**Comment by FantaMagier** [comment]
same issue

**Comment by RodrigoSMarques** [comment]
Closed. No activity in the last 14 days.
If necessary open again.
