### ISSUE TITLE
File Upload erro: Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by d3roch4** [parse-community/Parse-SDK-Flutter#660]
I have upload a file to server, but always return this erro: 
```
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/home/andre/projetos/rifa/parse-server/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/home/andre/projetos/rifa/parse-server/node_modules/body-parser/lib/types/json.js:83:15)
    at /home/andre/projetos/rifa/parse-server/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/andre/projetos/rifa/parse-server/node_modules/raw-body/index.js:224:16)
    at done (/home/andre/projetos/rifa/parse-server/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/andre/projetos/rifa/parse-server/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

My code to send is:
```
Future<void> alterarImagemRifa() async {
    var img = await ImagePicker().getImage(source: ImageSource.gallery);
    ParseFileBase parseFile;
    if (kIsWeb) {
      parseFile = ParseWebFile(await img.readAsBytes(), name: 'imagens/rifa_${rifa.id}', debug: true);
    } else {
      parseFile = ParseFile(File(img.path), name: 'imagens/rifa_${rifa.id}');
    }

    obj.set('imagem', parseFile );
    var resp = await obj.save().catchError(erroSnack);
    if(!resp.success)
      return erroSnack('Não foi possível enviar o arquivo ao servidor', StackTrace.current);
    rifa.imagem = parseFile.url;
  }
```

**Comment by RodrigoSMarques** [comment]
André, vou responder em português mesmo para ficar mais fácil.

Acredito que o problema é o nome do arquivo. Você está colocando uma "imagens/" no nome do arquivo".

O nome do arquivo deve ser "imagem.png", "imagem.jgp", este é o nome que você vê, mas internamente o Parse vai gerar outro nome para a URL do arquivo.

**Comment by d3roch4** [comment]
Foi exatamente isso, removi a '/' e funcionou. O estranho é que dá um erro
de Json, o que me deixou perdido.

Muito obrigado pela dica!

Em seg, 26 de jul de 2021 11:41, Rodrigo de Souza Marques <
***@***.***> escreveu:
