### ISSUE TITLE
"Exception: Error running pod install" when installing parse_server_sdk_flutter

### ISSUE THREAD

**Issue by pbrandl** [parse-community/Parse-SDK-Flutter#965]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
I am trying to run my flutter app while having `parse_server_sdk_flutter` specified as my dependency.

### Steps to reproduce
Specifying `parse_server_sdk_flutter: ^6.0.0` (also tried 5.1.2), then running `flutter pub get` and running the app.

### Actual Outcome
The following output is given:

```
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    [!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find `Runner`. 
    /Users/peter/.gem/ruby/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer/target_inspector.rb:108:in `compute_targets'
    /Users/peter/.gem/ruby/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer/target_inspector.rb:40:in `compute_results'
   ...
    /Users/peter/.gem/ruby/2.6.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Exception: Error running pod install
Exited
```

### Expected Outcome
I expected the app to run as before since I only got the `parse_server_sdk_flutter` as a new dependency.

### Environment
- SDK version: 6.0.0 and 5.1.2
- Flutter version: 3.7.12
- Dart version: 2.19.6
- Operating system version: macOS Ventura 13.3.1 (MacBook Air M2, 2022)

**Comment by pbrandl** [comment]
Not sure, where did this error come from. I removed the `macos` folder (also read about the `ios` folder that could cause this problem). Afterwards I ran `flutter create --platforms=macos .` within my flutter project. This seemed to solve the issue and I could start my project again.

**Comment by pbrandl** [comment]
Not sure, where did this error come from. I removed the `macos` folder (also read about the `ios` folder that could cause this problem). Afterwards I ran `flutter create --platforms=macos .` within my flutter project. This seemed to solve the issue and I could start my project again.
